name: 3dgs
channels:
  - pytorch
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - plyfile
  - python=3.9.13
  - pip=24.2
  - pytorch=2.4.0
  - pytorch-cuda=12.4
  - torchaudio=2.4.0
  - torchvision==0.19.0
  - tqdm
  - pip:
    - submodules/diff-gaussian-rasterization
    - submodules/simple-knn
